//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empleados_TFI_PAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_recibo
    {
        public int id_detalle { get; set; }
        public int num_recibo { get; set; }
        public string des_concepto { get; set; }
        public Nullable<double> cantidad { get; set; }
        public string deb_o_cred { get; set; }
        public Nullable<double> sueldo_base { get; set; }
    
        public virtual recibo_sueldo recibo_sueldo { get; set; }
    }
}
