//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empleados_TFI_PAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empleado()
        {
            this.empleado1 = new HashSet<empleado>();
            this.recibo_sueldo = new HashSet<recibo_sueldo>();
        }
    
        public int id_empleado { get; set; }
        public int dni { get; set; }
        public int id_rol { get; set; }
        public int id_depto { get; set; }
        public int id_supervisor { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string direccion { get; set; }
        public string mail { get; set; }
        public Nullable<int> telefono { get; set; }
        public Nullable<System.DateTime> fecha_nac { get; set; }
    
        public virtual departamento departamento { get; set; }
        public virtual rol rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empleado> empleado1 { get; set; }
        public virtual empleado empleado2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recibo_sueldo> recibo_sueldo { get; set; }
    }
}
