//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empleados_TFI_PAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class recibo_sueldo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public recibo_sueldo()
        {
            this.detalle_recibo = new HashSet<detalle_recibo>();
        }
    
        public int num_recibo { get; set; }
        public int id_empleado { get; set; }
        public Nullable<System.DateTime> fecha_liq { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_recibo> detalle_recibo { get; set; }
        public virtual empleado empleado { get; set; }
    }
}
